### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by S-kus** [walterbender/starchart#9]
The activity has no Readme.md file. It will help the newbies to understand the activity in a better way.

I would like to add it with the help of Sugar’s documentation!

**Comment by S-kus** [comment]
@quozl what are your opinions about this?

**Comment by quozl** [comment]
Thanks.  Interesting question.  My assessment of the activity situation is not a simple answer.
* the latest release of the activity was in 2015, for Python 2 and GTK 3, and;
* work to port to Python 3 and GTK 3 was in progress but has stalled because of regressions.

So work on a README.md file is not nearly as necessary as work toward a release, but if that's all you have time for there's no reason why that work could not be merged.  However, your argument that it will help newbies to understand the activity doesn't seem well thought out.  The source code and commit history is straightforward, and no developer should have much difficulty getting started.  Non-developers could be told that the activity is not available because work is needed.

Now, of course, I feel terribly silly.  In the time it took me to make this assessment and write it up, I could have written the README.md.

**Comment by S-kus** [comment]
Okay, Thank you @quozl. I am closing this issue.
Sorry for the inconvenience.

**Comment by quozl** [comment]
It's okay, I wasn't inconvenienced.  I have a lot of spare time right now.
